## TASK 1

## Business Understanding
"Customer churn is the rate at which customers stop doing business with a company. Losing a customer costs more than it seems, because replacing them requires marketing and sales expense, and the company also loses the future revenue that customer would have generated over time. The goal of the prediction model is to calculate a probability score showing how likely each customer is to churn, which gives more useful information than a simple yes/no answer. With this score, a company can group customers into risk tiers, and when a customer's churn probability crosses a high threshold (for example 70%), the company can proactively offer discounts or incentives to retain them, while lower-risk customers can simply be monitored."

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [4]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
df.shape

(7043, 21)

In [6]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.9 MB

In [8]:
df['TotalCharges']

0         29.85
1        1889.5
2        108.15
3       1840.75
4        151.65
         ...
7038     1990.5
7039     7362.9
7040     346.45
7041      306.6
7042     6844.5
Name: TotalCharges, Length: 7043, dtype: str

In [9]:
df['TotalCharges'].unique()

<ArrowStringArray>
[  '29.85',  '1889.5',  '108.15', '1840.75',  '151.65',   '820.5',  '1949.4',
   '301.9', '3046.05', '3487.95',
 ...
 '2625.25', '6886.25',  '1495.1',   '743.3',  '1419.4',  '1990.5',  '7362.9',
  '346.45',   '306.6',  '6844.5']
Length: 6531, dtype: str

In [10]:
df[df['TotalCharges'] == ' ']

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

In [11]:
df[df['TotalCharges'] == ' ']['Churn']

488     No
753     No
936     No
1082    No
1340    No
3331    No
3826    No
4380    No
5218    No
6670    No
6754    No
Name: Churn, dtype: str

In [12]:
df[df['TotalCharges'] == ' ']['Churn'].value_counts()

Churn
No    11
Name: count, dtype: int64

In [15]:
pd.to_numeric(df['TotalCharges'], errors='coerce')

0         29.85
1       1889.50
2        108.15
3       1840.75
4        151.65
         ...
7038    1990.50
7039    7362.90
7040     346.45
7041     306.60
7042    6844.50
Name: TotalCharges, Length: 7043, dtype: float64

In [16]:
##error='coerce' for if you can't convert something, don't crash just replace it with NaN

In [18]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [24]:
##coercion confirmation
df['TotalCharges'].isnull().sum()

np.int64(11)

In [25]:
##filling the NaN with 0
df['TotalCharges'] = df['TotalCharges'].fillna(0)

In [26]:
##make sure there are no missing values
print(df['TotalCharges'].isnull().sum())
print(df['TotalCharges'].dtype)

0
float64

TASK 4

In [27]:
##check for duplicated rows

In [28]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
7038    False
7039    False
7040    False
7041    False
7042    False
Length: 7043, dtype: bool

In [30]:
##number of duplicated rows
df.duplicated().sum()

np.int64(0)

In [31]:
df['customerID'].duplicated().sum()

np.int64(0)

CustomerID is unique per customer so expect 0

In [32]:
##check category columns for inconsistent values(eg. 'yes' & 'Yes' & 'yes ')

In [34]:
for col in df.select_dtypes(include='str').columns:
    print(col, ':', df[col].unique())

customerID : <ArrowStringArray>
['7590-VHVEG', '5575-GNVDE', '3668-QPYBK', '7795-CFOCW', '9237-HQITU',
 '9305-CDSKC', '1452-KIOVK', '6713-OKOMC', '7892-POOKP', '6388-TABGU',
 ...
 '9767-FFLEM', '0639-TSIQW', '8456-QDAVC', '7750-EYXWZ', '2569-WGERO',
 '6840-RESVB', '2234-XADUH', '4801-JZAZL', '8361-LTMKD', '3186-AJIEK']
Length: 7043, dtype: str
gender : <ArrowStringArray>
['Female', 'Male']
Length: 2, dtype: str
Partner : <ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str
Dependents : <ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str
PhoneService : <ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str
MultipleLines : <ArrowStringArray>
['No phone service', 'No', 'Yes']
Length: 3, dtype: str
InternetService : <ArrowStringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str
OnlineSecurity : <ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
OnlineBackup : <ArrowStringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str
DeviceProtection : <ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
TechSupport : <ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
StreamingTV : <ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
StreamingMovies : <ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str
Contract : <ArrowStringArray>
['Month-to-month', 'One year', 'Two year']
Length: 3, dtype: str
PaperlessBilling : <ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str
PaymentMethod : <ArrowStringArray>
[         'Electronic check',              'Mailed check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str
Churn : <ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

In [36]:
for col in df.select_dtypes(include='str').columns:
    print(col, ':', df[col].unique())
    print()

customerID : <ArrowStringArray>
['7590-VHVEG', '5575-GNVDE', '3668-QPYBK', '7795-CFOCW', '9237-HQITU',
 '9305-CDSKC', '1452-KIOVK', '6713-OKOMC', '7892-POOKP', '6388-TABGU',
 ...
 '9767-FFLEM', '0639-TSIQW', '8456-QDAVC', '7750-EYXWZ', '2569-WGERO',
 '6840-RESVB', '2234-XADUH', '4801-JZAZL', '8361-LTMKD', '3186-AJIEK']
Length: 7043, dtype: str

gender : <ArrowStringArray>
['Female', 'Male']
Length: 2, dtype: str

Partner : <ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

Dependents : <ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

PhoneService : <ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

MultipleLines : <ArrowStringArray>
['No phone service', 'No', 'Yes']
Length: 3, dtype: str

InternetService : <ArrowStringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str

OnlineSecurity : <ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

OnlineBackup : <ArrowStringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str

DeviceProtection : <ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

TechSupport : <ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

StreamingTV : <ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

StreamingMovies : <ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

Contract : <ArrowStringArray>
['Month-to-month', 'One year', 'Two year']
Length: 3, dtype: str

PaperlessBilling : <ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

PaymentMethod : <ArrowStringArray>
[         'Electronic check',              'Mailed check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str

Churn : <ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

TASK 5

In [37]:
##Analysing the Target Variable

In [38]:
df['Churn'].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [39]:
df['Churn'].value_counts(normalize=True)*100
#normalize=True converts raw counts into (0 to 1) proportions

Churn
No     73.463013
Yes    26.536987
Name: proportion, dtype: float64

TASK 3

In [40]:
##DATA DICTIONARY

In [41]:
df.dtypes

customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges        float64
Churn                   str
dtype: object

## Data Dictionary

| Feature | Description | Type |
|---|---|---|
| customerID | Unique identifier assigned to each customer. | Categorical (ID) |
| gender | The customer's self-identified gender. | Categorical |
| SeniorCitizen | Whether the customer is a senior citizen (1 if yes, 0 otherwise). | Numerical (binary) |
| Partner | Whether the customer has a permanent partner living with them. | Categorical |
| Dependents | Whether the customer relies on dependents in their household. | Categorical |
| tenure | The number of months the customer has been actively subscribed to our service. | Numerical (Count) |
| PhoneService | Whether the customer has an active phone line service with us. | Categorical |
| MultipleLines | Whether the customer uses multiple phone lines at their location. | Categorical |
| InternetService | The type of internet service provided. | Categorical |
| OnlineSecurity | Whether the customer subscribed to online security services. | Categorical |
| OnlineBackup | Whether the customer subscribed to an online backup service. | Categorical |
| DeviceProtection | Whether the customer subscribed to device protection services. | Categorical |
| TechSupport | Whether the customer subscribed to technical support services. | Categorical |
| StreamingTV | Whether the customer uses streaming television services. | Categorical |
| StreamingMovies | Whether the customer uses streaming movie services. | Categorical |
| Contract | The length of the service contract. | Categorical |
| PaperlessBilling | Whether the customer opted for paperless monthly billing statements. | Categorical |
| PaymentMethod | The method the customer uses to pay their bill. | Categorical |
| MonthlyCharges | The amount charged to the customer each month. | Numerical (Continuous) |
| TotalCharges | The accumulated sum of all charges billed to the customer over their tenure. | Numerical (Continuous) |
| Churn | Whether or not the customer left the company during the contract period. | Target (Categorical) |

## Data Quality Report

**Missing Values:** Found 11 rows with missing values in the TotalCharges column, where the missing values appeared as blank spaces (' ') rather than standard nulls, which is why they weren't caught by initial null checks. All 11 rows had a tenure of 0, meaning these were customers who had not yet completed a billing cycle, so no total charge had accumulated yet. All 11 were also non-churned customers. Handled by converting the column to numeric with pd.to_numeric(errors='coerce'), which converted the blanks to NaN, then filling those NaN values with 0, since a tenure of 0 mathematically corresponds to zero total charges billed.

**Duplicate Records:** Checked using df.duplicated() and found 0 duplicate rows across the full dataset. Also checked customerID specifically using df['customerID'].duplicated() and found 0 duplicates, confirming each customer appears exactly once.

**Data Type Issues:** The TotalCharges column was stored as text (object/str) instead of a numeric type, despite containing numeric values, because 11 rows contained a blank space instead of a number. Fixed by converting the column with pd.to_numeric(errors='coerce') followed by filling missing values with 0, resulting in a correct float64 dtype.

**Categorical Consistency:** Checked all 16 categorical columns for typos, inconsistent capitalization, and stray whitespace using .unique() on each column. Found no inconsistencies; all categorical values were clean and consistently formatted. Noted that several service-related columns (OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies) include a third value, "No internet service," which is a valid category rather than an error, since customers without internet service cannot have internet-dependent add-ons.

In [44]:
df.to_csv('telco_churn_cleaned.csv', index=False)